### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by payne911** [meta-dog/meta-dog#40]
First of all, good job with this website! I absolutely appreciate the effort that went into this. :)
And by the way, you may want to edit your README to include a link to [your backend repo](https://github.com/meta-dog/meta-bones as well.

Anyways, here are my questions:
1. This seems to be working even though I'm based in Canada (which is not a listed country in their introduction message). Is this normal, or maybe your intro msg should be updated)?
2. If I click to get an app referral, but do not use it before it expires (7 days I think), can I claim another referral for that same app afterward?
3. Does the 25% off apply to games that are on sale? For example, if a game is currently sold at 50% off, how does the extra 25% apply?
4. I added a bunch of my own referral links. Will the Oculus app notify me when someone uses one?
5. If someone uses a referral link of mine, are the credits automatically added to my account? Or is there some kind of deadline before which I must accept the credits else they are simply lost?
6. The website mentions "MAX 30" when submitting a referral link: how do I know how many I've submitted? And since those links actually expire after 7 days, am I supposed to keep going back to the website to resubmit links after a week? And this would count toward my max of 30 every single time, or this only applies to active referral links?

**Comment by davidciglesias** [comment]
Hey! Thanks for the feedback!

I've added the link to the Readme as per your suggestion 😄 

Regarding the answers.

1. Canada is included now, and you're right that it's a translation issue! Just pushed a commit to fix this
2. Yes! If you get one and it expires, you can open the same link in 7 days or just get a new one if you want
3. No, sale games are excluded, and the referrals will not apply even if the sale has a lower discount
4. In the Meta Quest App there's a new section for referrals, found in the Menu. In there, you should see App referrals, and you actually have to manually claim the credit from there 14 days after the referral has been used to buy a game.
5. See above; you have to go to the App and claim it; afaik there's no limit
6. MAX 30 means you can only submit 30 referrals at once in that form. It's a simple limit to avoid someone misusing the system. And the links don't expire in 7 days, what expires is the usage of the codes for the "friend". The code remains the same unless you change your username.

Let me know if you have further questions!

**Comment by payne911** [comment]
Thanks for the quick replies!

> MAX 30 means you can only submit 30 referrals at once in that form.

Ah, so I can paste multiple links in this text field? I think if you want to make this more obvious, in terms of UI/UX, it should instead display the referral ID in a "badge" with an associated "X" to remove that element, and to the right of the text field there should be a "x/30" counter that updates as people add referrals to the list.

---
By the way, you may want to consider adding a FAQ section to your website so that these answers don't get lost. I suspect a few people may have wondered about the same things. :)

Also, a few more recommendations:
1. It could be interesting to display next to each app/game how many active referral links already exist. This may help save some space in your DB by discouraging people to add their own if they see there are already 6000 people that submitted theirs. (Or to provide some insight into the chances of actually getting a reward from the referral.)
2. Moreover, have you considered different approaches to the referral selection mechanism? It could be interesting to keep a counter of how often a link was used, and to lower the associated weight to achieve a "weighed random sample". Or there could be a MinHeap used so that you randomly select among the lowest referral scores. This would result in encouraging more contributions from your users. (Although to be honest, the current fully-random approach is probably the fairest approach.)

---
Oh, and you forgot to edit the README's list of countries
![image](https://github.com/meta-dog/meta-dog/assets/38117856/1140610b-b730-4e93-b18e-cde44a41092b)

**Comment by davidciglesias** [comment]
Thanks for the recommendations! 😄 

I'm not sure that the bulk upload system is used very much, and I'd actually prefer to discourage its use, as I've been hit with 800+ verifications for a single that were essentially invalid in their majority in the past (and only 30 or so with games they owned)

In regards to displaying how many active referral links... I'd like to avoid providing any such information, as it can cause a lot of trouble (say Meta asks for the data or for it to be removed).

As to the selection mechanism... I did consider your option in the past, but I can't really tell how often a link has been used in reality, only how often it has been pulled from the list (not even that currently, as I don't store that kind of info). This can also lead to not-so-pure intents as people can spam referrals to ensure that their old referral has the same chance as any other, and in general, to demands of how often one's referral has been used, which is not the main goal of meta-dog, which is to allow anyone to get easily discounts, rather than people getting referral money.

By the way, there is a FAQ, which is the first thing you see when you enter, and I've added some points that were missing 😄

**Comment by payne911** [comment]
Very good points, thanks for sharing.

> I'm not sure that the bulk upload system is used very much

This makes me think you might not have telemetry setup on this project. You may want to consider some of the free services just to help you see which features are used the most, how much traffic your website gets, etc.
As an example, here is how I do it on my own open-source project (`ga` stands for "Google Analytics"): https://github.com/useful-forks/useful-forks.github.io/blob/master/website/src/analytics-wrapper.js

Moreover, you may want to edit your repo's `About` section to include a link to your website. Similar to this:
![image](https://github.com/meta-dog/meta-dog/assets/38117856/4708898b-a6b1-463d-9f65-f7692bd02a92)
And since you aren't using Releases nor Packages, you may want to unselect those
![image](https://github.com/meta-dog/meta-dog/assets/38117856/1f5a49d2-a014-43d3-940e-6feff00aeabb)

You may also have noticed I created [a Chrome Extension for my tool](https://chrome.google.com/webstore/detail/useful-forks/aflbdmaojedofngiigjpnlabhginodbf): you could probably do something similar which adds a little button in the Oculus Store page of each individual app (it would fetch a code directly, or simply redirect people on your page with the appropriate pre-filled filters to allow them to quickly get a code).

Finally, note that I appended `.github.io` to my repo's name: that allows you to get a shorter URL, and is [what GitHub suggests when you setup your GitHub Pages](https://pages.github.com/):
![image](https://github.com/meta-dog/meta-dog/assets/38117856/b9e7d1c7-aed6-4013-8c9e-3b781a8dba3d)
You could be getting https://meta-dog.github.io/ as the URL instead of https://meta-dog.github.io/meta-dog/.
Keep in mind that after doing that, you may want to consider adding a rerouting from your old URL to your new one.

**Comment by davidciglesias** [comment]
Thanks for the comments!

To be honest, it was a conscious choice to not have any kind of telemetry. When the project started, it was never clear whether there was going to be some kind of c&d from Meta, so gathering any kind of info (even usage, even anonymous) was out of the question.

At this stage the project is mostly in maintenance mode, and I expect that rather sooner than later (maybe 2024?) Meta will stop the referrals (or at least severely limit them), which will mean the end of the tool.

Don't take this comment as ungrateful, but I'm afraid I still do not currently wish to add more telemetry, and mostly dedicate time on it to fix the verification process, which keeps receiving breaking changes.

**Comment by payne911** [comment]
Absolutely no worries.
Thanks again for creating this 👍
