### ISSUE TITLE
I wanna check that my refferal code is properly added

### ISSUE THREAD

**Issue by bang7851** [meta-dog/meta-dog#43]
I added the code to your site, but I'm not sure whether or not I did it properly.
But I couldn't find the way to check the refferal I did in the website. Could I get the way to check my refferal?

**Comment by davidciglesias** [comment]
Hi @bang7851 thanks for the comment 😄 

The only way you can check is attempt to put it again in the system; this will let you know if it was already placed in the queue, or if it was verified or blacklisted due to being invalid.

No other ways exist as they prevent people abusing the system.
