### ISSUE TITLE
When I enter my app refferal code again to check that my refferal is properly applied, what message is popped up when I did properly?

### ISSUE THREAD

**Issue by bang7851** [meta-dog/meta-dog#44]
I entered my app refferal code again to check if my code is properly added, and I got the message "You sent a link from the user xxx in the past, but you pasted a link from the user xxx now. Only one user is allowed". If this pops up, is my code properly added? If not, what should I do?

**Comment by davidciglesias** [comment]
Hi, this happens because you have used links from two different usernames, and the app attempts to prevent people adding referral from others 

You can clear your browser's local storage or use incognito if you want to check.
